name: Close Stale Issues

on:
  schedule:
    # at 1:30
    - cron: '30 1 * * *'

jobs:
  close-stale-prs-issues:
    # Don't run on forks
    if: github.repository == 'sebastienros/fluid'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/stale@v8
        with:
          stale-issue-message: >
            This is an automated message. Per our repo policy, stale issues get closed if there has been no activity in the past 15 days. The issue will be automatically closed in 7 days. If you wish to keep this issue open, please add a new comment.
          stale-issue-label: stale
          days-before-pr-stale: -1
          days-before-issue-stale: 15
          days-before-issue-close: 7
          only-issue-labels: needs author feedback
          operations-per-run: 20